#https://github.com/hassio-addons/addon-ubuntu-base
build_from:
  aarch64: "ghcr.io/hassio-addons/ubuntu-base/aarch64:10.0.1"
  amd64: "ghcr.io/hassio-addons/ubuntu-base/amd64:10.0.1"
  armv7: "ghcr.io/hassio-addons/ubuntu-base/armv7:10.0.1"