worker_processes 1;
pid /var/run/nginx.pid;
error_log stderr;

events {
    worker_connections 64;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log off;
    sendfile on;

    server {
        listen 8099;
        root /root/weewx-data/public_html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
